apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: testrs
          image: busybox555
  replicas: 5
  selector:
    matchLabels:
      tier: frontend
