apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: k8session

spec:
  volumes:
    - name: ep-volume
      emptyDir:
        sizeLimit: 500Mi
  containers:
    - image: nginx
      name: pod1-nginx
      volumeMounts:
        - mountPath: /shared/vignesh
          name: ep-volume
    - image: paulbouwer/hello-kubernetes
      name: pod2-busybox
      volumeMounts:
        - mountPath: /shared/abeer
          name: ep-volume
