apiVersion: v1
kind: PersistentVolume
metadata:
  name: paluguna-pv-volume
  namespace: k8session
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
    