apiVersion: v1
kind: pod
metadata:
  labels:
    run: webapp
    name: webapp
spec:
  volumes:
    - name: webapp-vol
      hostPath:
        path: var/log/webapp
  containers:
    - image: kodekloud/event-simulator
      name: webapp
      volumeMounts:
        - name: webapp-vol
          mountPath: /log
