apiVersion: v1
kind: PersistentVolumeCliam
metadata:
  name: pal-pv-claim
  namespace: k8session
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"