apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podexmp
  name: podexmp
  namespace: k8session
spec:
  volumes:
  - name: ep-volume
    emptyDir: 
      sizeLimit: 500Mi
  containers:
  - image: nginx
    name: podexmp
    volumeMounts:
      - mounthPath: /shared/volume
        name: ep-volume



       



 