apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-dev
  name: nginx-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-dev
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-dev
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
