apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podenv
  name: podenv
  namespace: k8session
spec:
  containers:
    - env:
        - name: DNS_DOAMIN
          value: cluster
        - name: POD_NAMESPACE
          value: default
      image: nginx
      name: podenv
